for the second check

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,16 +1,26 @@
-#!/bin/bash/env bash
-# Check the no. of parameters
-if [ $# -lt 4 ]; then
-  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+#!/usr/bin/env bash
+# Checking for interpreter arguments,
+if [ $# -lt 4 ]
+then
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
 fi
 
-# Assign the parameters to variables
-FILE=$1
-IP=$2
-USER=$3
-KEY=$4
+# Assigning Arguments to var,
 
-# Transfer the file to user home directory on the server
-scp -i $KEY -o StrictHostKeyChecking=no $FILE $USER@$IP:~/
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
 
+
+# Disabbling Strict Host Key checking,
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# Check if  transfer was successful,
+if [ $? -eq 0 ]
+then
+  echo "FILE TRANSFER WAS SUCCESSFULL"
+else
+  echo "FILE TRANSFER FAILED"
+fi
